### ISSUE TITLE
Cannot receive messages

### ISSUE THREAD

**Issue by bonfus** [ggerganov/ggwave-java#2]
Hi there,
I compiled the code after updating to gradle 7.4 and everything is fine except for message receiving.

I'm working with the emulator of android studio 22 which is apparently correctly recording audio from the laptop, but I never manage to decode a message. Was it working for you or there are known problems with the emulator?

Also, why is this hard coded?

https://github.com/ggerganov/ggwave-java/blob/211ae947fda7307aa318cd430216bcabd9b8d071/app/src/main/java/com/example/ggwave/MainActivity.java#L225

Thanks!

**Comment by ggerganov** [comment]
It's been a while - last time I tested this, it worked.
But now I don't have an environment setup so I cannot confirm.

Line 225 looks strange - not sure why it is there.

**Comment by bonfus** [comment]
I have a clue, android records arrays of zeros.

**Comment by bonfus** [comment]
Ok, it's a problem with the emulator and pipewire.

I managed to get it working with
```
./emulator -avd IMAGE -audio alsa -allow-host-audio ...
```
but only from time to time, sometimes audio capturing fails.

Edit: this seems to work consistently `./emulator -avd NME -qemu -allow-host-audio`
